### ISSUE TITLE
AttributeError: DensityRatioEstimator instance has no attribute '_sigma'

### ISSUE THREAD

**Issue by damhurmuller** [srome/pykliep#2]
Traceback (most recent call last):
  File "challenge.py", line 187, in <module>
    weights = kliep.predict(X)    
  File "challenge.py", line 180, in predict
    return np.dot(self._phi(X, sigma=sigma), self._alpha).reshape((X.shape[0],))
  File "challenge.py", line 150, in _phi
    sigma = self._sigma
AttributeError: DensityRatioEstimator instance has no attribute '_sigma'

**Comment by xiaochenwang94** [comment]
I have same problem.

**Comment by jonmart0304** [comment]
When you run as python3 this issue goes away

**Comment by jonmart0304** [comment]
I think it needs to be initialized in the constructor first because it is out of scope?

**Comment by usccolumbia** [comment]
if the runnig does not converge, this code returns without setting the _sigma, so get the error.

            if len(sorted_scores) == 0:   
                warnings.warn('LCV failed to converge for all values of sigma.')
                return self
            self._sigma = sorted_scores[0][0][1]

**Comment by ramdhan1989** [comment]
I have some problem

**Comment by liaochen1988** [comment]
I have the same problem

**Comment by atakanfilgoz** [comment]
As @usccolumbia mentioned if the run does not converge, this code does not set _sigma variable and it throws exception. You can try larger sigmas based on your data to avoid.

**Comment by SSMK-wq** [comment]
What was done to solve this issue? I also get the same error. Is anyone here tried anything to fix this issue? and how did you fix it? I already tried changing the list of values (for sigma) in code to larger values such as 100
